import {Inter} from 'next/font/google';
import '../app/styles/globals.css';
import type {ReactNode} from 'react';
import {Suspense} from 'react';
import 'react-toastify/dist/ReactToastify.css';
import {Box} from '@mui/material';
import {ThemeProvider} from '@/app/components/common/Theme/ThemeProvider';
import {Layout} from '@/app/components/common/Layout/Layout';
import {Flip, ToastContainer} from 'react-toastify';
import {ModalProvider} from '@/app/components/common/Modal/ModalProvider';
import Loading from '@/app/loading';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html suppressHydrationWarning lang='en'>
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <ThemeProvider>
            <ToastContainer
              style={{marginTop: '60px'}}
              autoClose={3000}
              limit={3}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme='colored'
              transition={Flip}
            />
            <ModalProvider />
            <Layout>
              <Box
                sx={{
                  marginTop: '50px',
                  marginBottom: '70px',
                  paddingX: {xs: 2, sm: 3, md: 4},
                }}
              >
                {children}
              </Box>
            </Layout>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
