import {Inter} from 'next/font/google';
import '../app/styles/globals.css';
import type {ReactNode} from 'react';
import {Flip, ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import {Box} from '@mui/material';
import {Bar} from '@/app/components/common/Bar/Bar';
import {Savings, Toll} from '@mui/icons-material';
import {ThemeProvider} from '@/app/components/common/Theme/ThemeProvider';
import {ThemeIcon} from '@/app/components/common/Theme/ThemeIcon';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html suppressHydrationWarning lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <ToastContainer
            style={{marginTop: '60px'}}
            autoClose={3000}
            limit={3}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme='colored'
            transition={Flip}
          />
          <Bar
            position='top'
            items={[
              {
                content: (
                  <>
                    <Toll sx={{marginRight: '10px'}} />
                    Invest
                  </>
                ),
                textAlign: 'left',
              },
              {content: <ThemeIcon />, textAlign: 'right'},
            ]}
          />
          <Box
            sx={{
              marginTop: '80px',
              marginBottom: '70px',
              paddingX: {xs: 2, sm: 3, md: 4, lg: 5},
            }}
          >
            {children}
          </Box>
          <Bar
            position='bottom'
            items={[
              {
                content: (
                  <>
                    <Savings sx={{marginRight: '10px'}} />
                    Invest
                  </>
                ),
                textAlign: 'left',
              },
              {
                content: '© 2024 Invest. All rights reserved.',
                textAlign: 'right',
              },
            ]}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
