import {Inter} from 'next/font/google';
import '../app/styles/globals.css';
import type {ReactNode} from 'react';
import {Flip, ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import {Box} from '@mui/material';
import {ThemeProvider} from '@/app/components/common/Theme/ThemeProvider';
import {Layout} from '@/app/components/ui/Layout/Layout';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html suppressHydrationWarning lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <ToastContainer
            style={{marginTop: '60px'}}
            autoClose={3000}
            limit={3}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme='colored'
            transition={Flip}
          />
          <Layout>
            <Box
              sx={{
                marginTop: '80px',
                marginBottom: '70px',
                paddingX: {xs: 2, sm: 3, md: 4, lg: 5},
              }}
            >
              {children}
            </Box>
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
