version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: investmentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/investmentdb"

volumes:
  postgres_data:
