import {Inter} from 'next/font/google';
import '../styles/globals.css';
import type {ReactNode} from 'react';
import 'react-toastify/dist/ReactToastify.css';
import {Box} from '@mui/material';
import {AuthenticatedLayout} from '@/app/components/common/Layout/AuthenticatedLayout';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <Box className={inter.className}>
      <AuthenticatedLayout>
        <Box
          sx={{
            marginTop: '50px',
            marginBottom: '70px',
            paddingX: {xs: 2, sm: 3, md: 4, lg: 5},
          }}
        >
          {children}
        </Box>
      </AuthenticatedLayout>
    </Box>
  );
}
